
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instagram_development

  <<: *default
  database: instagram_test

#
production:
  <<: *default
  database: instagram_production
  username: instagram
  password: <%= ENV['INSTAGRAM_DATABASE_PASSWORD'] %>
